version: '3'

services:
    mirror-offline:
        # image: mirror-offline:latest
        build: ./mirror-offline-docker
        environment:
            - PLUGIN_WEBSITE=http://google.com/
            - PLUGIN_FOLDER=google.com
        ports:
            - 80:80
            - 443:443
