version: '3'

services:
    wget:
        build: ./wget
        image: wget-website
        environment:
            - PLUGIN_WEBSITE=https://google.com
            - PLUGIN_USER=
            - PLUGIN_PASSWORD=
            - PLUGIN_MIRROR=/
        volumes:
            - ./html:/tmp
    nginx:
        build: ./nginx
        image: nginx-website
        volumes:
            - ./html/google.com:/usr/share/nginx/html
        ports:
            - 80:80
            - 443:443
volumes:
    html:
        driver: local
