version: '3'

services:
    wget-mirror-health:
        build: ./mirror-offline
        image: wget-offline
        environment:
            - PLUGIN_WEBSITE=https://www.google.com
            - PLUGIN_USER=
            - PLUGIN_PASSWORD=
            - PLUGIN_MIRROR=http://localhost/
        volumes:
            - ./html:/tmp
    nginx:
        build: ./nginx
        image: nginx-website
        volumes:
            - ./html:/usr/share/nginx/html
        ports:
            - 80:80
            - 443:443
volumes:
    html:
        driver: local
