version: '3'

services:
    mirror-offline:
        build: ./mirror-offline-docker
        image: mirror-offline:latest
        environment:
            - PLUGIN_WEBSITE=https://google.com
        ports:
            - 80:80
            - 443:443
